services:
  backend:
    container_name: summarizer_backend
    build:
      context: ./backend
    ports:
      - "8000:8000"  # Use consistent port 8000 for simplicity
    volumes:
      - ./backend:/app
      - ./models:/app/models
      # Updated uploads path to be inside the backend directory
      - ./backend/uploads:/app/uploads
      - pip_cache:/root/.cache/pip
    environment:
      - MODEL_PATH=${MODEL_PATH:-./models/llama-2-7b.Q4_K_M.gguf}
      - HUGGINGFACE_MODEL_ID=${HUGGINGFACE_MODEL_ID:-TheBloke/Llama-2-7B-GGUF}
      - HUGGINGFACE_FILENAME=${HUGGINGFACE_FILENAME:-llama-2-7b.Q4_K_M.gguf}
      - GPU_LAYERS=40
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    container_name: summarizer_frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"  # Use consistent port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000  # Match the backend port
    depends_on:
      - backend

volumes:
  pip_cache: