# version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # Match Vite default
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000  # Change to localhost instead of research-agent
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
  grobid:
    image: lfoppiano/grobid:0.7.2
    ports:
      - "8070:8070"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive || echo 'Service starting'"]
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 180s

  research-agent:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - grobid